# Generated by Django 4.2.6 on 2023-12-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
