# Generated by Django 4.2.6 on 2024-01-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appointment_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visited_time',
            field=models.DateTimeField(null=True),
        ),
    ]
