# Generated by Django 4.2.6 on 2024-02-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_doctor_latitude_doctor_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_remarks',
            field=models.TextField(null=True),
        ),
    ]
