# Generated by Django 4.2.6 on 2024-02-04 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='predicted_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='prescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='symptoms',
            field=models.TextField(null=True),
        ),
    ]
