# Generated by Django 4.2.6 on 2024-02-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
