# Generated by Django 4.2.6 on 2024-02-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='report',
            name='scheduled_time',
        ),
    ]
