# Generated by Django 4.2.6 on 2024-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_report_doctor_remove_report_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
