# Generated by Django 4.2.6 on 2024-02-23 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
