# Generated by Django 4.2.6 on 2024-02-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_create_superuser'),
        ('home', '0020_user_picture'),
    ]

    operations = [
    ]
